feat: use new top level wash commands
wasmCloud/wasmcloud.com pull request #101
Opened 2023-06-06 12:52 UTC by vados-cosmonic

## Feature or Problem

Add top level `wash` commands to the documentation, replacing relevant existing uses of `wash ctl <x>`

See also: https://github.com/wasmCloud/wash/issues/538

## Related Issues

https://github.com/wasmCloud/wash/issues/538

## Release Information

## Consumer Impact

## Testing

Built on platform(s)
- [ ] x86_64-linux
- [ ] aarch64-linux
- [ ] x86_64-darwin
- [ ] aarch64-darwin
- [ ] x86_64-windows

Tested on platform(s)
- [ ] x86_64-linux
- [ ] aarch64-linux
- [ ] x86_64-darwin
- [ ] aarch64-darwin
- [ ] x86_64-windows

### Unit Test(s)

### Acceptance or Integration

### Manual Verification

2023-06-06 14:05 UTC, brooksmtownsend requested changes
It's surprising how much cleaner the commands look, especially without `ctl` and things.

Only blocking on us releasing wash 0.18

2023-06-06 16:28 UTC, connorsmith256 requested changes
Looks like there are still some references to `wash reg` and `wash claims` that should be updated now too

2023-06-06 16:28 UTC, connorsmith256 commented on blog/better-together-building-efficient-microservices-in-kubernetes-with-webassembly.md
> +Previous guides used `wash ctl start` which is deprecated and will be replaced by `wash start` in a future version
Same comment everywhere. The "will be replaced by wash start" kinda sounds like `wash start` isn't available yet, but the code snippets show that it is

```suggestion
Previous guides used `wash ctl start`, which is now deprecated and will be removed in a future version
```

2023-06-07 11:17 UTC, vados-cosmonic commented on blog/better-together-building-efficient-microservices-in-kubernetes-with-webassembly.md
> +Previous guides used `wash ctl start` which is deprecated and will be replaced by `wash start` in a future version
- [ ] fix wording on deprecation

2023-06-07 11:23 UTC, vados-cosmonic commented
Oh sorry @brooksmtownsend re-requested review from you when we're still waiting on wash `0.18`.

2023-06-07 17:12 UTC, connorsmith256 approved these changes
Woohoo!

2023-06-07 17:13 UTC, connorsmith256 commented
(Still waiting to merge until after v0.18 is released)

2023-06-13 19:20 UTC, brooksmtownsend approved these changes
good to go!

2023-06-13 19:34 UTC, merged