added notes for 08-23
wasmCloud/wasmcloud.com pull request #148
Opened 2023-08-23 17:51 UTC by brooksmtownsend

Thanks Lachlan for the community notes!

2023-08-23 18:06 UTC, lachieh requested changes

2023-08-23 18:06 UTC, lachieh commented on community/2023-08-23-community-meeting.md
> +  - #wasmcloud in CNCF slack.
```suggestion
- **Questions**
  - What big areas are left in OTP > Rust parity? CJ.
    - [implement get operations for link defs and claims](https://github.com/wasmCloud/wasmCloud/issues/480).
    - [validate actor and provider claims upon start](https://github.com/wasmCloud/wasmCloud/issues/554).
    - [implement policy checking and management](https://github.com/wasmCloud/wasmCloud/issues/480).
    - [chunking for large payloads](https://github.com/wasmCloud/wasmCloud/issues/482).
  - Where to ask questions? Dave Tessman.
    - [https://slack.wasmcloud.com](https://slack.wasmcloud.com)
    - #wasmcloud in [CNCF slack](https://communityinviter.com/apps/cloud-native/cncf).
```

2023-08-23 18:06 UTC, lachieh commented on community/2023-08-23-community-meeting.md
> +- **WASMCON**
```suggestion
- [**WASMCON**](https://events.linuxfoundation.org/wasmcon/)
```

2023-08-23 23:29 UTC, lachieh approved these changes

2023-08-29 14:22 UTC, CazJT approved these changes
Notes look good to me.

2023-08-29 14:22 UTC, merged