Adding blog post on algebraic effects
wasmCloud/wasmcloud.com pull request #24
Opened 2022-05-24 18:29 UTC by autodidaddict

Signed-off-by: Kevin Hoffman <autodidaddict@users.noreply.github.com>

2022-05-24 19:58 UTC, thomastaylor312 approved these changes
This is a fun post. LGTM

2022-05-24 19:58 UTC, thomastaylor312 commented on content/english/blog/caps_are_effects.md
> +date: 2022-05-24T9:00:00-04:00
Nit: Make sure to update this to the actual publish date before merge

2022-05-24 20:12 UTC, brooksmtownsend requested changes

2022-05-24 20:12 UTC, brooksmtownsend commented on content/english/blog/caps_are_effects.md
> +In wasmCloud, we manage algebraic effects through [capability providers](https://wasmcloud.dev/reference/host-runtime/capabilities/). Here the capability provider, as seen by the WebAssembly module (
If you surround the hyperlinks here with `<u>` tags they will actually show as underlined

2022-05-24 20:12 UTC, brooksmtownsend commented on content/english/blog/caps_are_effects.md
> +wasmCloud takes these algebraic effects even further by requiring each of our WebAssembly modules to be [cryptographically signed](https://wasmcloud.dev/reference/host-runtime/security/) with the exp
same comment re: hyperlinks here with `<u>` tags

2022-05-24 20:12 UTC, brooksmtownsend commented on content/english/blog/caps_are_effects.md
> +If you're interested in learning more about capabilities and seeing them in action, take a look at our [examples](https://github.com/wasmcloud/examples/) repository.
same comment re: hyperlinks here with `<u>` tags

2022-05-25 13:34 UTC, brooksmtownsend approved these changes

2022-05-25 16:56 UTC, merged