feat(mdx): change to shiki for syntax highlighting
wasmCloud/wasmcloud.com pull request #297
Opened 2024-02-13 22:03 UTC by lachieh

## Feature or Problem
Adds syntax highlighting for `wit` and `smithy` through [`shiki`](http://shiki.style/) as a rehype markdown plugin.

2024-02-14 11:55 UTC, vados-cosmonic requested changes, later dismissed
This looks good -- we've finally fixed the problem with the `<code>` stuff being in dark mode even when light mode was selected. 

But one thing is missing -- the copy button isn't on the new Shiki-powered code sections -- and it would be nice if the language in use was in the top right too)

2024-02-15 14:21 UTC, brooksmtownsend requested changes
![image](https://github.com/wasmCloud/wasmcloud.com/assets/12040685/c6deb8da-f6aa-4354-ae90-ca1f3190d0cb)

I think it looks great in the code sections and at least in the last commit I can copy things 😄 I'm unsure if shiki has support for the docusaurus highlighting though

2024-02-15 19:09 UTC, brooksmtownsend commented
@lachieh looks like some of the highlighting is back and looks great 😄 just @ me for a full review when ready

2024-02-15 19:24 UTC, lachieh commented
Alright gang, I've added highlighting, diffing and focus support through the use of `@shiki/transformers` ([docs](https://shiki.style/packages/transformers)):

https://github.com/wasmCloud/wasmcloud.com/assets/1687902/12ea3afa-eee0-4f76-ad32-198d95a30d75

2024-02-15 19:24 UTC, brooksmtownsend reviewed
It looks like the removed lines still copy in as a newline return
```rust
        response_body
            .write()
            .unwrap()

            .blocking_write_and_flush(format!("Hello, {}!\n", name).as_bytes()) 
            .unwrap();
```

2024-02-15 19:24 UTC, brooksmtownsend commented on docs/tour/adding-capabilities.mdx
> +    // Make sure to remove the _ prefix from the `request` variable // [!code ++]
We can kill this comment now 😄

2024-02-15 19:25 UTC, lachieh commented on docs/tour/adding-capabilities.mdx
> +    // Make sure to remove the _ prefix from the `request` variable // [!code ++]
good point, got the python one too

2024-02-15 19:40 UTC, lachieh commented
@brooksmtownsend updated the copy logic to get rid of those newlines

2024-02-15 19:41 UTC, brooksmtownsend approved these changes

2024-02-21 18:44 UTC, merged