Add CRUD key-value example
wasmCloud/wasmcloud.com pull request #351
Opened 2024-04-02 19:28 UTC by ericgregory

Adding CRUD with `wasi:keyvalue` example (and an "examples" menu item).

2024-04-09 13:38 UTC, brooksmtownsend requested changes
This example looks fantastic! Requesting changes here just around code highlighting and indentation to make the page look better 🚀

2024-04-09 13:38 UTC, brooksmtownsend commented on versioned_docs/version-0.82/examples/cruddy.mdx
> +}
For some reason this section doesn't actually highlight 🤔

2024-04-09 13:38 UTC, brooksmtownsend commented on versioned_docs/version-0.82/examples/cruddy.mdx
> +	/// In this interface, we use the term `bucket` to refer to a collection of key-value
This code that's indented ends up showing on the preview, could we de-indent this?

2024-04-09 13:38 UTC, brooksmtownsend commented on versioned_docs/version-0.82/examples/cruddy.mdx
> +            // [!code ++]
Same comment here re: indentation

2024-04-09 13:38 UTC, brooksmtownsend commented on versioned_docs/version-0.82/examples/cruddy.mdx
> +	description: "CRUD demo" // [!code ++]
Same comment here re: indentation

2024-04-09 13:38 UTC, brooksmtownsend commented on versioned_docs/version-0.82/examples/cruddy.mdx
> +  export wasi:http/incoming-handler@0.2.0;
Same comment here re: code highlighting

2024-04-09 13:38 UTC, brooksmtownsend commented on versioned_docs/version-0.82/examples/cruddy.mdx
> +```
Same comment here re: indentation

2024-04-09 13:38 UTC, brooksmtownsend commented on versioned_docs/version-0.82/examples/cruddy.mdx
> +	/// can very depending on the specific implementation. For example,
Same comment here re: indentation

2024-04-09 13:38 UTC, brooksmtownsend commented on versioned_docs/version-0.82/examples/cruddy.mdx
> +	// In the language of WASI, here we're creating a new bucket resource
Same comment here re: indentation

2024-04-09 13:38 UTC, brooksmtownsend commented on versioned_docs/version-0.82/examples/cruddy.mdx
> +	// Create a variable for outgoing values - Put/sets will use this
Same comment here re: indentation

2024-04-09 13:38 UTC, brooksmtownsend commented on versioned_docs/version-0.82/examples/cruddy.mdx
> +	httpResponse.SetStatusCode(200)
Same comment here re: indentation

2024-04-09 13:38 UTC, brooksmtownsend commented on versioned_docs/version-0.82/examples/cruddy.mdx
> +	description: "CRUD demo" // [!code ++]
Same comment here re: indentation

2024-04-09 13:38 UTC, brooksmtownsend commented on versioned_docs/version-0.82/examples/cruddy.mdx
> +   * `set-status-code` method.
Same comment here re: indentation

2024-04-09 13:38 UTC, brooksmtownsend commented on versioned_docs/version-0.82/examples/cruddy.mdx
> +
Same comment here re: indentation

2024-04-09 13:38 UTC, brooksmtownsend commented on versioned_docs/version-0.82/examples/cruddy.mdx
> +	///
Same comment here re: indentation

2024-04-09 13:38 UTC, brooksmtownsend commented on versioned_docs/version-0.82/examples/cruddy.mdx
> +	description: "CRUD demo" # [!code ++]
Same comment here re: indentation

2024-04-09 13:38 UTC, brooksmtownsend commented on versioned_docs/version-0.82/examples/cruddy.mdx
> +	/// It is worth noting that the exact terminology for bucket in key-value stores
Same comment here re: indentation

2024-04-09 13:38 UTC, brooksmtownsend commented on versioned_docs/version-0.82/examples/cruddy.mdx
> +            # [!code ++]
Same comment here re: indentation

2024-04-09 13:38 UTC, brooksmtownsend commented on versioned_docs/version-0.82/examples/cruddy.mdx
> +	description: "CRUD demo" // [!code ++]
Same comment here re: indentation

2024-04-09 14:46 UTC, lachieh commented on versioned_docs/version-0.82/examples/cruddy.mdx
> +```
```suggestion
```wit
```

2024-04-09 14:46 UTC, lachieh commented on versioned_docs/version-0.82/examples/cruddy.mdx
> +```
```suggestion
```wit
```

2024-04-09 14:47 UTC, lachieh commented on versioned_docs/version-0.82/examples/cruddy.mdx
> +```
```suggestion
```wit
```

2024-04-09 14:48 UTC, lachieh commented on versioned_docs/version-0.82/examples/cruddy.mdx
> +```
```suggestion
```wit
```

2024-04-09 14:48 UTC, lachieh commented on versioned_docs/version-0.82/examples/cruddy.mdx
> +```
```suggestion
```wit
```

2024-04-09 14:49 UTC, lachieh commented on versioned_docs/version-0.82/examples/cruddy.mdx
> +```
```suggestion
```wit
```

2024-04-09 14:49 UTC, lachieh commented on versioned_docs/version-0.82/examples/cruddy.mdx
> +```
```suggestion
```wit
```

2024-04-09 14:50 UTC, lachieh commented on versioned_docs/version-0.82/examples/cruddy.mdx
> +```
```suggestion
```wit
```

2024-04-09 14:51 UTC, lachieh commented on versioned_docs/version-0.82/examples/cruddy.mdx
> +```shell
```suggestion
```
```

2024-04-09 14:52 UTC, lachieh commented on versioned_docs/version-0.82/examples/cruddy.mdx
> +```
````suggestion

```
├── app.py
├── build
├── wadm.yaml
├── wasmcloud.toml
└── wit
```
````

2024-04-09 14:53 UTC, lachieh commented on versioned_docs/version-0.82/examples/cruddy.mdx
> +```
```suggestion
```wit
/// Represents an outgoing HTTP Request.
resource outgoing-request 
```
```

2024-04-09 14:53 UTC, lachieh commented on versioned_docs/version-0.82/examples/cruddy.mdx
> +world hello {
```suggestion
```wit
package wasmcloud:hello;

world hello {
```

2024-04-09 14:53 UTC, lachieh commented on versioned_docs/version-0.82/examples/cruddy.mdx
> +```
```suggestion
```wit
```

2024-04-09 15:00 UTC, lachieh approved these changes
This is great! The content flows nicely and I like the multi-language parts. Minor nit and the rest are syntax highlighting changes.

2024-04-09 15:00 UTC, lachieh commented on versioned_docs/version-0.82/examples/cruddy.mdx
> +## Conclusion
I think I'd prefer to see this section called "Next Steps", still keeping the same content. If this is the structure you've got for the other ones, then I think I'd like to see them changed too, but not as an immediate priority.

2024-04-10 14:29 UTC, brooksmtownsend commented
Took a look and it looks like a lot of the highlighting is fixed, I just see some indentation still at least in the TinyGo piece 🙂

2024-04-10 14:44 UTC, ericgregory commented on versioned_docs/version-0.82/examples/cruddy.mdx
> +## Conclusion
Makes sense, done!

2024-04-10 15:09 UTC, ericgregory commented
> Took a look and it looks like a lot of the highlighting is fixed, I just see some indentation still at least in the TinyGo piece 🙂

Should be all set now!

2024-04-11 19:23 UTC, brooksmtownsend approved these changes
Looks awesome!

2024-04-11 19:24 UTC, merged