CNCF Kubernetes Blog Cross-Post
wasmCloud/wasmcloud.com pull request #485
Opened 2024-07-01 10:56 UTC by CazJT

## Feature or Problem

## Related Issues

## Release Information

## Consumer Impact

## Testing

### Unit Test(s)

### Acceptance or Integration

### Manual Verification

2024-07-04 11:47 UTC, lachieh commented on blog/extending-kubernetes-frontiers-components/index.mdx
> +WebAssembly (Wasm) components are here and [already unlocking new computing patterns](previous-CNCF-piece-link-TK). Meanwhile, CNCF's [**wasmCloud**](https://wasmcloud.com/) offers Wasm-native orches
```suggestion
WebAssembly (Wasm) components are here and [already unlocking new computing patterns](#previous-CNCF-piece-link-TK). Meanwhile, CNCF's [**wasmCloud**](https://wasmcloud.com/) offers Wasm-native orchestration for distributed components&mdash;in essence, a Kubernetes for WebAssembly.
```

just changing for build

2024-07-04 11:49 UTC, lachieh requested changes
Looks good, requesting changes to prevent merge with missing link

2024-07-04 11:49 UTC, lachieh commented on blog/extending-kubernetes-frontiers-components/index.mdx
> +WebAssembly (Wasm) components are here and [already unlocking new computing patterns](#previous-CNCF-piece-link-TK). Meanwhile, CNCF's [**wasmCloud**](https://wasmcloud.com/) offers Wasm-native orche
This link will need to be corrected before merge

2024-07-08 13:07 UTC, CazJT commented
@lachieh changed the link to one of Bailey's talks as it is excellent and also contains a longer blog on the page. Check everything is in order. I adjusted in codespace and updated the branch. This hasn't been working amazingly and so there may be issues.

2024-07-09 12:47 UTC, lachieh approved these changes

2024-07-09 12:47 UTC, lachieh commented on blog/extending-kubernetes-frontiers-components/index.mdx
> +
```suggestion

{/* truncate */}

```

2024-07-09 12:48 UTC, merged