Tweak/docs onboarding
wasmCloud/wasmcloud.com pull request #74
Opened 2023-04-26 21:44 UTC by connorsmith256

## Feature or Problem
This PR:
- updates the "Get Started Today️" button to the "Getting Started" page
- formats the Installation page and adds one note about editing `PATH`
- reformats, updates images, and streamlines the "Getting Started" page. The biggest change is the removal of references to `wash call`, since this is likely to be confusing to new users. I also consolidated some terminology

The goal is to make a new user's experience with the onboarding docs a little more straightforward

2023-04-27 11:12 UTC, LiamRandall commented
I would like to see the install instructions on the home page.

<img width="977" alt="Screenshot 2023-04-27 at 7 10 48 AM" src="https://user-images.githubusercontent.com/1530656/234845482-8c999842-1477-412b-b377-3bafbe8eb881.png">

2023-04-28 18:02 UTC, brooksmtownsend requested changes
One nit but the content looks great

2023-04-28 18:02 UTC, brooksmtownsend commented on docs/getting-started.mdx
> +  VAG3QITQQ2ODAOWB5TTQSDJ53XK3SHBEIFNK4AYJ5RKAX2UNSCAPHA5M    N/A                default            wasmcloud.azurecr.io/httpserver:0.17.0
These N/A's should be names 🤔 Here's what I see
```
  Actor ID                                                   Name                      Image Reference                          
  MBCFOPM6JW2APJLXJD3Z5O4CN7CPYJ2B4FTKLJUR5YR5MITIU7HD3WD5   Echo                      wasmcloud.azurecr.io/echo:0.3.8          
                                                                                                                                
  Provider ID                                                Name                      Link Name                  Image Reference
  VAG3QITQQ2ODAOWB5TTQSDJ53XK3SHBEIFNK4AYJ5RKAX2UNSCAPHA5M   HTTP Server               default                    wasmcloud.azurecr.io/httpserver:0.17.0
```

2023-04-28 18:52 UTC, brooksmtownsend approved these changes

2023-04-28 19:01 UTC, merged