Reorganizing navigation and document order
wasmCloud/wasmcloud.com pull request #75
Opened 2023-05-02 18:25 UTC by autodidaddict

Reorganizes the left navigation and the flow of documents to be more ergonomic for the reader and to better facilitate progressive learning.

NOTE that this PR currently only contains the reorganization. There are a number of empty pages here that need to be filled out.

2023-05-03 14:15 UTC, stephenandary commented
I have found a few instances in preview where an "i" appears before a title. I am not sure if that is desired, but I will try to edit this comment with where I have seen them. I am not sure if it was done by this PR as when I searched for line in healthcheck under elixer for example it was not part of edited text. 

ElixirOTP/healthcheck.md
![image](https://user-images.githubusercontent.com/12686470/235942438-bc6e769a-70da-42c3-bb27-cf174a687b04.png)

2023-05-03 14:22 UTC, autodidaddict commented
> I have found a few instances in preview where an "i" appears before a title. I am not sure if that is desired, but I will try to edit this comment with where I have seen them. I am not sure if it was done by this PR as when I searched for line in healthcheck under elixer for example it was not part of edited text.
> 
> ElixirOTP/healthcheck.md ![image](https://user-images.githubusercontent.com/12686470/235942438-bc6e769a-70da-42c3-bb27-cf174a687b04.png)
> 
> ElixirOTP/safeshutdown.md ![image](https://user-images.githubusercontent.com/12686470/235942795-6ef15a31-91ff-4f28-b882-0e0f277ff624.png)

The markdown includes things like `:::info` and so on. These produce differently styled boxes. They're fine and get rendered nice and pretty in the preview.

2023-05-04 16:19 UTC, connorsmith256 requested changes
A couple nits/suggestions, and I found some remaining TBD pages:

- wasmCloud in Production -> Overview
- wasmCloud in Production -> Artifact Registries
- wasmCloud in Production -> Securing Applications -> Running a Policy Service
- Reference -> FAQ
- Reference -> Glossary

2023-05-04 16:19 UTC, connorsmith256 commented on docs/fundamentals/capabilities/create-provider/new-interface.md
> +These check the file against a predefined set of rules. The rules will be added to an improved over time.
Supernit: "added to and improved over time"

2023-05-04 16:19 UTC, connorsmith256 commented on docs/fundamentals/wadm/_category_.json
> +    "label": "Managed Application Deployment",
Suggestion: I think `wadm` should be in the title here:
- "Managed Application Deployment (wadm)" or
- "wadm: Managed Application Deployment" or
- "Managed Application Deployment with wadm"

2023-05-04 16:19 UTC, connorsmith256 commented on docs/fundamentals/wadm/usage.md
> +title: "Using Wadm via Wash"
Do we capitalize wadm and wash when using title case, or leave them lowercase?

2023-05-04 16:19 UTC, connorsmith256 commented on docs/production/index.md
> +TBD
Ah, looks like this needs to be updated

2023-05-04 16:55 UTC, connorsmith256 approved these changes

2023-05-04 18:31 UTC, merged